//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtTerm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AtTerm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///    &lt;configSections&gt;
        ///        &lt;sectionGroup name=&quot;userSettings&quot; type=&quot;System.Configuration.UserSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot; &gt;
        ///            &lt;section name=&quot;AtTerm.Properties.Settings&quot; type=&quot;System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot; allowExeDefinition=&quot;MachineToLocalUser&quot; requirePermission=&quot;false&quot; /&gt;
        ///        &lt;/sectio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string App {
            get {
                return ResourceManager.GetString("App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AT+CFUN=&lt;fun&gt;,&lt;fun&gt;
        ///AT+CMGR
        ///ATE&lt;fun&gt;
        ///AT+QPOWD=&lt;fun&gt;
        ///AT+QGNSSC=&lt;fun&gt;
        ///AT+QIACT
        ///AT+CGACT=&lt;fun&gt;[,&lt;fun&gt;]
        ///AT+QGNSSRD=&lt;fun&gt;
        ///AT+QGNSSRD?
        ///AT+CSQ
        ///AT+CREG?
        ///AT+CREG=&lt;fun&gt;
        ///AT+CGSN
        ///AT+GSN
        ///AT+QNSTATUS
        ///AT+QLTS
        ///AT+QNITZ=&lt;fun&gt;
        ///AT+CTZU?
        ///AT+CTZR=&lt;fun&gt;
        ///AT+CTZR?
        ///AT+CTZR=&lt;fun&gt;
        ///AT+QSIMDET=&lt;fun&gt;,&lt;fun&gt;,&lt;fun&gt;
        ///AT+QSIMSTAT?
        ///AT+QSIMSTAT=&lt;fun&gt;
        ///AT+CCID
        ///AT+QCCID
        ///AT+COPS?
        ///AT+COPS=&lt;fun&gt;[,&lt;fun&gt;[,&lt;fun&gt;]]
        ///AT+CPOL?
        ///AT+CPOL=&lt;fun&gt;[,&lt;fun&gt;[,&lt;fun&gt;]]
        ///AT+COPN
        ///AT+QENG?
        ///AT+QENG=&lt;fun&gt;[,&lt;fun&gt;]
        ///ATA
        ///AT+CLCC
        ///ATD&lt;fun&gt;;
        ///ATH0        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Commands {
            get {
                return ResourceManager.GetString("Commands", resourceCulture);
            }
        }
    }
}
